### ISSUE TITLE
Readme examples and ExampleRepo are not updated

### ISSUE THREAD

**Issue by stomper3579** [pksprojects/ElasticSwift#79] opened 2020-03-25 18:42 UTC
Are there requirements for this to work beyond what's in the readme?  I've tried the code samples you supply but there are numerous errors throughout.  Especially in the Search section, .match doesn't exist.

**Comment by prafsoni** [comment] 2020-03-25 21:41
@stomper3579 I believe you are talking about this 
`let match = try QueryBuilders.matchQuery().match(field: "myField", value: "MySearchValue").build()` 

QueryBuilders and Quries are part of ElasticSwiftQueryDSL
Did you tried
`import ElasticSwiftQueryDSL` ?

**Comment by stomper3579** [comment] 2020-03-25 22:42
I did include that import yes.
It says: Value of type 'MatchQueryBuilder' has no member 'match'

**Comment by prafsoni** [comment] 2020-03-25 23:02
@stomper3579 It looks like I missed some of the sections in README while updating it.

Please, refer: https://github.com/pksprojects/ElasticSwift/blob/c87a7129880103a1870a2d75a668cb465c4e347e/Tests/ElasticSwiftTests/ElasticSwiftTests.swift#L302

https://github.com/pksprojects/ElasticSwift/blob/c87a7129880103a1870a2d75a668cb465c4e347e/Tests/ElasticSwiftTests/ElasticSwiftTests.swift#L285

**Comment by prafsoni** [comment] 2020-03-26 02:55
Updated examples in [ElasticSwiftExamples](https://github.com/pksprojects/ElasticSwiftExamples) to `1.0.0-alpha.10`

**Comment by stomper3579** [comment] 2020-03-26 19:39
Thank you!  That compiles without errors now.  Unfortunately now I get the error: 
Error Domain=NSURLErrorDomain Code=-999 "cancelled"

Here is my function based off of the readme.
I've checked the url and credentials with postman to confirm they are good.

```
func parse() {
        
        let credentials: ClientCredential = BasicClientCredential(username: ES_USERNAME, password: ES_PASSWORD)
        let settings = Settings(forHost: ES_URL_STRING, withCredentials: credentials, adaptorConfig: URLSessionAdaptorConfiguration.default)
        let client = ElasticClient(settings: settings)
        
        let queryBuilder = QueryBuilders.boolQuery()
        
        do {
            let match = try QueryBuilders.matchQuery().set(field: "last_name").set(value: "m").build()

            queryBuilder.must(query: match)
            let query =  try queryBuilder.build()
            
            let sort =  SortBuilders.fieldSort("last_name")
                .set(order: .asc)
                .build()
            
            let request = try SearchRequestBuilder()
                .set(indices: "leads_primary")
                //.set(types: "lead")
                .set(query: query)
                .set(sort: sort)
                .build()

            client.search(request, completionHandler: handler)
            
        }
        catch {
            print("Unexpected error: \(error).")
        }
    }

    func handler(_ result: Result<SearchResponse<String>, Error>) -> Void {
        switch result {
        case .failure(let error):
            print("Error", error)
        case .success(let response):
            print("Response", response)
        }
    }
```

**Comment by prafsoni** [comment] 2020-03-26 19:57
I will need a few more details about your setup.

1. What is the target platform?
2. Using cocopods/spm?
3. Swift/Xcode version ?

**Comment by stomper3579** [comment] 2020-03-26 20:25
Xcode 11.2.1 just iPhone
swift 4.2
cocoapods
```
pod 'ElasticSwift', '~> 1.0.0-alpha.10'
pod 'ElasticSwiftCore', '~> 1.0.0-alpha.10'
pod 'ElasticSwiftQueryDSL', '~> 1.0.0-alpha.10'
pod 'ElasticSwiftCodableUtils', '~> 1.0.0-alpha.10'
pod 'ElasticSwiftNetworking', '~> 1.0.0-alpha.10'
```

**Comment by stomper3579** [comment] 2020-03-26 20:26
Not sure where all that strikethrough came from

**Comment by prafsoni** [comment] 2020-03-27 00:38
strikethrough lines were because of `~>`

**Comment by prafsoni** [comment] 2020-03-27 00:59
As of `v1.0.0-alpha.6` ElasticSwift requires swift `5.0` and above. Not sure how it's compiling for you maybe Xcode is handling it for you. 

Since request execution is completely async and based on the above snippet `client` is initialized inside `parse`, the `client` is deallocated shortly after it goes out of scope. As a result, any pending tasks are cancelled.

I would also recommend looking at example ios app [here](https://github.com/pksprojects/ElasticSwiftExamples/tree/master/ElasticSwiftSample-iOS) and thread [here](https://stackoverflow.com/questions/16073519/nsurlerrordomain-error-code-999-in-ios)

**Comment by stomper3579** [comment] 2020-03-27 20:45
Thank you for helping me in this.  I'm using swift 5.0 and your example helped me clean up my code some. I'm now creating the client in ViewDidLoad.
my new function looks like this:
```
func parse() {
        
        do {
            let query = try QueryBuilders.matchQuery().set(field: "query").set(value: "mouse").build()
            
            let request = try SearchRequestBuilder()
                .set(indices: "leads_primary")
                .set(size: 5)
                .set(query: query)
                .build()
           
            client.search(request, completionHandler: handler)
            
        }
        catch {
            print("Unexpected error: \(error).")
        }
    }
```

Unfortunately I'm still getting the 999 error.  I've confirmed that I don't need a certificate and again I know that the credentials and URL are good as they've been tested in Postman.
Thanks again, I'd really appreciate it if you have any more suggestions.

**Comment by prafsoni** [comment] 2020-03-27 21:16
I don’t see anything wrong with the function as such. If you could provide a example app which reproduces the error in a repo and share link here. I can clone and investigate.

**Comment by prafsoni** [comment] 2020-04-28 05:36
afcdad1 Fixed ReadMe and updated [examples](https://github.com/pksprojects/ElasticSwiftExamples) to alpha.11

**Closed as completed by prafsoni** 2020-04-28 05:36 UTC
Labels: docs

**Comment by gauthierm** [comment] 2021-07-22 22:43
I get the -999 error as well using the URLSessionAdaptorConfiguration and an elasticsearch URL using https. IT works with the NIO example. My URL and certificate are also valid. It seems like maybe the URLSession adapter is not using any of the default certificate validation.

**Comment by keithburgoyne** [comment] 2021-07-22 22:58
Funny, I am also seeing the same thing. Using an `https` URL with `URLSessionAdaptorConfiguration.default`. I'm using Xcode 12.5.1, and Swift 5.

**Comment by gauthierm** [comment] 2021-07-22 23:51
Ok, after looking more into my issue it appears it's impossible to use HTTPS + URLSession adapter without a custom self-signed certificate. I'll file a separate issue.
